name = "langchain-cloudflare-nuxt-template"
main = "./.output/server/index.mjs"
compatibility_date = "2023-11-15"
compatibility_flags = [ "nodejs_compat" ]

[[vectorize]]
binding = "AI_KNOWLEDGE_VECTORIZE_INDEX" # available within your Worker on env.AI_KNOWLEDGE_VECTORIZE_INDEX
index_name = "langchain_ai_docs_index"

[[vectorize]]
binding = "CLOUDFLARE_KNOWLEDGE_VECTORIZE_INDEX" # available within your Worker on env.CLOUDFLARE_KNOWLEDGE_VECTORIZE_INDEX
index_name = "langchain_cloudflare_docs_index"

[ai]
binding = "AI"

[vars]
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_SESSION = "cloudflare-nuxt"