name = "langchain-worker"
main = "./.output/server/index.mjs"
compatibility_date = "2023-11-15"
compatibility_flags = [ "nodejs_compat" ]

[[vectorize]]
binding = "AI_KNOWLEDGE_VECTORIZE_INDEX" # available within your Worker on env.AI_KNOWLEDGE_VECTORIZE_INDEX
index_name = "langchain_ai_knowledge"

[[vectorize]]
binding = "CLOUDFLARE_KNOWLEDGE_VECTORIZE_INDEX" # available within your Worker on env.CLOUDFLARE_KNOWLEDGE_VECTORIZE_INDEX
index_name = "langchain_cloudflare_knowledge"

[ai]
binding = "AI"
